// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using MediaInAction.VideoService.SeriesNs;
using MediaInAction.VideoService.SeriesNs.Dtos;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

// ReSharper disable once CheckNamespace
namespace MediaInAction.VideoService.SeriesNs;

public interface IPublicSeriesAppService : IApplicationService
{
    Task<List<SeriesDto>> GetListAsync();

    Task<SeriesDto> GetAsync(Guid id);

    Task<List<SeriesDto>> GetSeriesListAsync(GetSeriesListInput filter);
}
