// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using MediaInAction.VideoService.SeriesNs;
using MediaInAction.VideoService.SeriesNs.Dtos;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace MediaInAction.VideoService.SeriesNs;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IPublicSeriesAppService), typeof(PublicSeriesClientProxy))]
public partial class PublicSeriesClientProxy : ClientProxyBase<IPublicSeriesAppService>, IPublicSeriesAppService
{
    public virtual async Task<List<SeriesDto>> GetListAsync()
    {
        return await RequestAsync<List<SeriesDto>>(nameof(GetListAsync));
    }

    public virtual async Task<SeriesDto> GetAsync(Guid id)
    {
        return await RequestAsync<SeriesDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<List<SeriesDto>> GetSeriesListAsync(GetSeriesListInput filter)
    {
        return await RequestAsync<List<SeriesDto>>(nameof(GetSeriesListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetSeriesListInput), filter }
        });
    }
}
