// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using MediaInAction.VideoService.SeriesAliasNs;
using MediaInAction.VideoService.SeriesNs;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace MediaInAction.VideoService.SeriesNs;

public class SeriesCreateDto
{
    public string Name { get; set; }

    public int FirstAiredYear { get; set; }

    public SeriesAliasCreateDto[] SeriesAliases { get; set; }

    public bool IsActive { get; set; }

    public string ImageName { get; set; }
}
