FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY MediaInAction ./MediaInAction
WORKDIR /src/MediaInAction/services/video/src/MediaInAction.VideoService.HttpApi.Host
RUN dotnet publish -c Release -o bin/Release/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /src/MediaInAction/services/video/src/MediaInAction.VideoService.HttpApi.Host/bin/Release/publish/ .
ENTRYPOINT ["dotnet", "MediaInAction.VideoService.HttpApi.Host.dll"]