// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using MediaInAction.Shared.Domain.Enums;
using MediaInAction.VideoService.ToBeMappedNs;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace MediaInAction.VideoService.ToBeMappedNs;

public class ToBeMappedCreateDto
{
    public string Alias { get; set; }

    public bool Processed { get; set; }

    public FromService FromService { get; set; }

    public string FromId { get; set; }

    public MediaType Type { get; set; }

    public int Tries { get; set; }
}
