apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-configmap
data:
  yarp.json: |-
    {
      "ReverseProxy": {
        "Routes": {
          "AbpApi": {
            "ClusterId": "Administration",
            "Match": {
              "Path": "/api/abp/{**catch-all}"
            }
          },
          "Identity Service": {
            "ClusterId": "Identity",
            "Match": {
              "Path": "/api/identity/{**everything}"
            }
          },
          "Identity Service Swagger": {
            "ClusterId": "Identity",
            "Match": {
              "Path": "/swagger-json/Identity/swagger/v1/swagger.json"
            },
            "Transforms": [
              { "PathRemovePrefix": "/swagger-json/Identity" }
            ]
          },
          "FeatureManagement": {
            "ClusterId": "Administration",
            "Match": {
              "Path": "/api/feature-management/{**everything}"
            }
          },
          "PermissionManagement": {
            "ClusterId": "Administration",
            "Match": {
              "Path": "/api/permission-management/{**everything}"
            }
          },
          "SettingManagement": {
            "ClusterId": "Administration",
            "Match": {
              "Path": "/api/setting-management/{**everything}"
            }
          },
          "Administration ServiceSwagger": {
            "ClusterId": "Administration",
            "Match": {
              "Path": "/swagger-json/Administration/swagger/v1/swagger.json"
            },
            "Transforms": [
              { "PathRemovePrefix": "/swagger-json/Administration" }
            ]
          },
          "File Service": {
            "ClusterId": "File",
            "Match": {
              "Path": "/api/file/{**everything}"
            }
          },
          "File Service Swagger": {
            "ClusterId": "File",
            "Match": {
              "Path": "/swagger-json/File/swagger/v1/swagger.json"
            },
            "Transforms": [
              { "PathRemovePrefix": "/swagger-json/File" }
            ]
          },
          "ProductPictures": {
            "ClusterId": "File",
            "Match": {
              "Path": "/product-images/{**everything}",
              "Methods": [ "GET" ]
            }
          },
          "Emby Service": {
            "ClusterId": "Emby",
            "Match": {
              "Path": "/api/emby/{**everything}"
            }
          },
          "Emby Service Swagger": {
            "ClusterId": "Emby",
            "Match": {
              "Path": "/swagger-json/Emby/swagger/v1/swagger.json"
            },
            "Transforms": [
              { "PathRemovePrefix": "/swagger-json/Emby" }
            ]
          },
          "Video Service": {
            "ClusterId": "Video",
            "Match": {
              "Path": "/api/video/{**everything}"
            }
          },
          "Video Service Swagger": {
            "ClusterId": "Video",
            "Match": {
              "Path": "/swagger-json/Video/swagger/v1/swagger.json"
            },
            "Transforms": [
              { "PathRemovePrefix": "/swagger-json/Video" }
            ]
          },
          "Cmskit Public Service": {
            "ClusterId": "CmsKit",
            "Match": {
              "Path": "/api/cms-kit-public/{**everything}"
            }
          },
          "Cmskit Admin Service": {
            "ClusterId": "CmsKit",
            "Match": {
              "Path": "/api/cms-kit-admin/{**everything}"
            }
          },
          "Cmskit Service Swagger": {
            "ClusterId": "CmsKit",
            "Match": {
              "Path": "/swagger-json/Cmskit/swagger/v1/swagger.json"
            },
            "Transforms": [
              { "PathRemovePrefix": "/swagger-json/Cmskit" }
            ]
          },
          "Payment Service": {
            "ClusterId": "Payment",
            "Match": {
              "Path": "/api/payment/{**everything}"
            }
          },
          "Payment Service Swagger": {
            "ClusterId": "Payment",
            "Match": {
              "Path": "/swagger-json/payment/swagger/v1/swagger.json"
            },
            "Transforms": [
              { "PathRemovePrefix": "/swagger-json/payment" }
            ]
          },
        },
        "Clusters": {
          "Identity": {
            "Destinations": {
              "destination1": {
                "Address": "{{ .Values.reRoutes.identityService.url }}",
                "MetaData": {
                  "PublicAddress": "{{ .Values.reRoutes.identityService.dns }}"
                }
              }
            }
          },
          "Administration": {
            "Destinations": {
              "destination1": {
                "Address": "{{ .Values.reRoutes.administrationService.url }}",
                "MetaData": {
                  "PublicAddress": "{{ .Values.reRoutes.administrationService.dns }}"
                }
              }
            }
          },
          "File": {
            "Destinations": {
              "destination1": {
                "Address": "{{ .Values.reRoutes.fileService.url }}",
                "MetaData": {
                  "PublicAddress": "{{ .Values.reRoutes.fileService.dns }}"
                }
              }
            }
          },
          "Emby": {
            "Destinations": {
              "destination1": {
                "Address": "{{ .Values.reRoutes.embyService.url }}",
                "MetaData": {
                  "PublicAddress": "{{ .Values.reRoutes.embyService.dns }}"
                }
              }
            }
          },
          "Video": {
            "Destinations": {
              "destination1": {
                "Address": "{{ .Values.reRoutes.videoService.url }}",
                "MetaData": {
                  "PublicAddress": "{{ .Values.reRoutes.videoService.dns }}"
                }
              }
            }
          },
          "CmsKit": {
            "Destinations": {
              "destination1": {
                "Address": "{{ .Values.reRoutes.cmskitService.url }}",
                "MetaData": {
                  "PublicAddress": "{{ .Values.reRoutes.cmskitService.dns }}"
                }
              }
            }
          },
          "Payment": {
            "Destinations": {
              "destination1": {
                "Address": "{{ .Values.reRoutes.paymentService.url }}",
                "MetaData": {
                  "PublicAddress": "{{ .Values.reRoutes.paymentService.dns }}"
                }
              }
            }
          }
        }
      }
    }