// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using MediaInAction.VideoService.EpisodeAliasNs;
using MediaInAction.VideoService.EpisodeNs;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace MediaInAction.VideoService.EpisodeNs;

public class EpisodeCreateDto
{
    public string SeriesName { get; set; }

    public string SeriesYear { get; set; }

    public Guid? SeriesId { get; set; }

    public int SeasonNum { get; set; }

    public int EpisodeNum { get; set; }

    public DateTime? AiredDate { get; set; }

    public string EpisodeName { get; set; }

    public EpisodeAliasCreateDto[] EpisodeCreateAliases { get; set; }
}
