// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using MediaInAction.VideoService.MovieNs;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace MediaInAction.VideoService.MovieNs;

public class MovieAliasCreateDto
{
    public string IdType { get; set; }

    public string IdValue { get; set; }
}
