// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using MediaInAction.Shared.Domain.Enums;
using MediaInAction.VideoService.MovieNs;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace MediaInAction.VideoService.MovieNs;

public class MovieCreateDto
{
    public string Name { get; set; }

    public int FirstAiredYear { get; set; }

    public string ImageName { get; set; }

    public MovieAliasCreateDto[] MovieAliases { get; set; }

    public bool IsActive { get; set; }

    public MediaStatus MediaStatus { get; set; }
}
