config:
  selfUrl: https://mia-st-gateway-public-web
  isOnK8s: "true"
  authServer:
    authority: http://mia-st-authserver
    requireHttpsMetadata: "false"
    swaggerClientId: WebGateway_Swagger
  dotnetEnv: Staging 
  redisHost: mia-st-redis
  rabbitmqHost: mia-st-rabbitmq
  elasticsearchHost: mia-st-elasticsearch

reRoutes:
  identityService:
    url: http://mia-st-identity
    dns: https://identity.mediainaction.dev
  administrationService:
    url: http://mia-st-administration
    dns: https://administration.mediainaction.dev
  fileService:
    url: http://mia-st-file
    dns: https://file.mediainaction.dev
  embyService:
    url: http://mia-st-emby
    dns: https://emby.mediainaction.dev
  videoService:
    url: http://mia-st-video
    dns: https://video.mediainaction.dev
  cmskitService:
    url: http://mia-st-cmskit
    dns: https://cmskit.mediainaction.dev
  paymentService:
    url: http://mia-st-payment
    dns: https://payment.mediainaction.dev

ingress:
  host: mia-st-gateway-web-public
  tlsSecret: mia-wildcard-tls

image:
  repository: mediainaction/gateway-web-public
  tag: latest
  pullPolicy: IfNotPresent

env: {}