// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using MediaInAction.VideoService.MovieNs.Dtos;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace MediaInAction.VideoService.MovieNs.Dtos;

public class GetMoviesInput
{
    public string Filter { get; set; }
}
