// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using MediaInAction.Shared.Domain.Enums;
using MediaInAction.VideoService.MovieAliasNs.Dtos;
using MediaInAction.VideoService.MovieNs.Dtos;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace MediaInAction.VideoService.MovieNs.Dtos;

public class MovieDto : EntityDto<Guid>
{
    public string Name { get; set; }

    public int FirstAiredYear { get; set; }

    public MediaType Type { get; set; }

    public MediaStatus MovieStatus { get; set; }

    public bool IsActive { get; set; }

    public MovieAliasDto[] MovieAliasDtos { get; set; }
}
