// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using MediaInAction.VideoService.EpisodeNs.Dtos;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace MediaInAction.VideoService.EpisodeNs.Dtos;

public class GetEpisodeInput
{
    public Guid SeriesId { get; set; }

    public int SeasonNum { get; set; }

    public int EpisodeNum { get; set; }
}
