config:
  selfUrl: https://admin.mediainaction.com
  gatewayUrl: https://www.gateway.mediainaction.com/
  authServer:
    authority: https://auth.mediainaction.com
    requireHttpsMetadata: "false"
    responseType: "code"
ingress:
  host: mia-st-web
  tlsSecret: mia-wildcard-tls

image:
  repository: mediainaction/app-web
  tag: latest
  pullPolicy: IfNotPresent

# Extra environment variables or configurations
env: {}