// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using MediaInAction.VideoService.ToBeMappedNs.Dtos;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace MediaInAction.VideoService.ToBeMappedNs.Dtos;

public class GetToBeMappedInput
{
    public string Alias { get; set; }
}
