name: video_service_build_test_publish

on:
  push:
    branches: [ "main"  ]
    paths-ignore:
      - "README.md"
  pull_request:
    branches: [ "main"  ]
    paths-ignore:
      - "README.md"
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build and Test Video Service
        uses: ./.github/actions/build-test
        if: success()
        id: build-test-video-step
        with:
          project-path: 'services/video/src/MediaInAction.VideoService.HttpApi.Host'
          tests-path: 'services/video/test/'
          # wildcard search for files with the ".cobertura.xml" extension in all subdirectories of the current directory
          # https://www.jamescroft.co.uk/combining-multiple-code-coverage-results-in-azure-devops/
          # https://stackoverflow.com/questions/53255065/dotnet-unit-test-with-coverlet-how-to-get-coverage-for-entire-solution-and-not
          reports-path: ${{ github.workspace }}/**/*.cobertura.xml
          reports-output-path: ${{ github.workspace }}/output/test-results
          service-name: 'Video'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Packages To ghcr
        if: success()
        uses: ./.github/actions/ghcr-publish
        with:
          service-name: 'Video'
          token: ${{ secrets.GITHUB_TOKEN }}
      